name: fetch-rss-feed

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://0x1.pt/feed.xml
          readme-section: feed
          empty-commits: false
          template: "* {{ published | date(\"YYYY\") }} [{{ title }}]({{ link }})"
